### model
model_name_or_path: lmms-lab/LLaVA-Video-7B-Qwen2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: racing_status_estimation_video
template: qwen_1_5
cutoff_len: 4096
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 24

### output
output_dir: saves/llava-next-video/lora/sft_1219
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
