### model
model_name_or_path: llava-hf/LLaVA-NeXT-Video-7B-32K-hf
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: racing_status_estimation_video_test
eval_dataset: racing_status_estimation_video_test
template: llava_next_video
cutoff_len: 32768
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 24

### output
output_dir: saves/llava-next-video/lora/sft_test
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
ignore_keys: ['past_key_values', 'image_hidden_states', 'video_hidden_states']

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
